<?php

namespace AppBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends EntityRepository
{
    public function createUser(\AppBundle\Entity\User $user)
    {
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush();
    }
    
    public function updateUser(\AppBundle\Entity\User $user)
    {
        $em = $this->getEntityManager();
        $em->persist($user);
        $em->flush();
    }
    
    
}
