# To get started with security, check out the documentation:
# http://symfony.com/doc/current/book/security.html

security:

    encoders:
        AppBundle\Entity\User:
            algorithm: bcrypt
            
    providers:
#        in_memory:
#            memory: 
#                users:
#                    admin:
#                        password: admin
#                        password: $2a$08$jHZj/wJfcVKlIwr5AvR78euJxYK7Ku5kURNhNx.7.CSIJ3Pq6LEPC
                        
        db_provider:
            entity:
                class: AppBundle:User
                property: username                        

    firewalls:
        # disables authentication for dev resources and the profiler
        dev:
            pattern: ^/(_(profiler|wdt))/
            security: false

        # disables authentication for resources (assets)
        resources:
            pattern: ^/(css|images|img|js|fonts)/
            security: false            
        
        # main firewall
        main:
            anonymous: ~
            provider: db_provider
            form_login:
                login_path: /login
                check_path: /login_check    
                csrf_token_generator: security.csrf.token_manager
                # csrf_provider: security.csrf.token_manager # ne pas utiliser même si cela figure sur la documentation. La doc n'est pas sync
            logout:
                path: /logout
                target: /

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/signup, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/, roles: IS_AUTHENTICATED_FULLY }
