# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
parameters:
#    parameter_name: value

services:
    
    app.user_repository:
        class: AppBundle\Repository\UserRepository
        factory: ["@doctrine", getRepository]
        arguments: 
            - AppBundle\Entity\User
            
            
    app.user_service:
        class: AppBundle\Service\UserService
        arguments: ['@app.user_repository', '@security.password_encoder', '%kernel.root_dir%']

